security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        # use your user class name here
        App\Entity\Customers:
            # bcrypt or sodium are recommended
            # sodium is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: md5
            iterations: 0
            encode_as_base64: false
    providers:
        in_memory: { memory: ~ }
        api_key_user_provider:
          id: App\Security\Jwt\ApiKeyUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        customer:
            anonymous: ~
            provider: api_key_user_provider
            stateless: true
            simple_preauth:
              authenticator: App\Security\Jwt\ApiKeyAuthenticator
            guard:
              authenticators:
                - App\Security\Jwt\JwtAuthenticator
    access_control:
        - { path: ^/api/auth, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
